version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.name=es-cluster"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "node.master=true"
      - "node.data=true"
      - "node.ingest=true"
      - "node.name=es-node.{{.Task.Slot}}.{{.Node.Hostname}}"
      - "LOGSPOUT=ignore"
    networks:
       - esnet
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.7.0
    environment:
      - LOGSPOUT=ignore
    networks:
      - esnet
    configs:
      - source: ls_config.v1
        target: /usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${ELASTIC_VERSION:-6.7.0}
    networks:
      - esnet
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
    environment:
      - SERVER_NAME=kibana.${DOMAIN:-localhost}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_HOST:-http://elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOST:-http://elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      - LOGSPOUT=ignore
    deploy:
      mode: replicated
      replicas: 1

networks:
  esnet:
    driver: overlay

configs:
  ls_config.v1:
    file: $PWD/logstash/config/logstash.conf
